language: python
python: 3.6
services:
  - docker
script: 
  - python3 baseline_builder/baseline_builder.py --type nightly --command cleanup --age 10
  - python3 baseline_builder/baseline_builder.py --type nightly --command checkout
  - python3 baseline_builder/baseline_builder.py --type nightly --command build
  - python3 baseline_builder/baseline_builder.py --type nightly --command push
install:
  - pip3 install -r ./requirements/requirements.txt
